version: '2'
services:
  freenet-patched:
    container_name: freenet-patched
    image: dern3rd/freenet
    # network_mode: "host"
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:9481:9481"
      - "12345:12345/udp"
      - "12346:12346/udp"
    volumes:
      - ./volumes/conf:/conf
      - ./volumes/data:/data
      - ./volumes/downloads:/downloads
